name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint-markdown:
    name: Lint Markdown
    uses: ./.github/workflows/lint-markdown.yml

  lint-and-publish-bicep:
    name: Lint and Publish Bicep
    uses: ./.github/workflows/lint-and-publish-bicep.yml
    permissions:
      contents: read

  lint-build-test-and-publish-backend-service:
    name: Lint, Build, Test and Publish Backend Service
    uses: ./.github/workflows/build-and-publish-backend-service.yml
    permissions:
      contents: read
      checks: write
      pull-requests: write

  build-and-publish-frontend-app:
    name: Build and Publish Frontend App
    uses: ./.github/workflows/build-and-publish-frontend-app.yml
    permissions:
      contents: read
      checks: write
      pull-requests: write
