name: Lint and Publish Bicep

on:
  workflow_call:

jobs:
  build-armtemplates:
    name: Lint and Publish Bicep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Lint Bicep
        run: |
          bicep lint ./infra/main.bicep

      - name: Publish Bicep as Workflow Artifact
        uses: actions/upload-artifact@v7
        with:
          name: infrastructure_bicep
          path: |
            ./infra/*.bicep
            ./infra/*.json
            ./infra/**/*
